title: Practical Java
description: Practical Programming in Java
author: Jeff Stride
baseurl: "/practicaljava"
url: "https://stride-edventures.github.io/practicaljava"

markdown: kramdown
highlighter: rouge
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap
  
remote_theme: sighingnow/jekyll-theme-gitbook

# Book structure
collections:
  chapters:
    output: true
    permalink: /:collection/:name/
